name: Проблемы с Дискордом
description: Для ботов на tech-сервере
labels: 
  - unmarked
  - discord

body:
  - type: input
    id: name
    attributes:
      label: Опишите проблему
      placeholder: Cжатое описание ошибки
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:  
      label: Шаги для воспроизведения поведения
      value: |
        1. Выполните команду "/remove member:@haffk ticket:001"
        2. Дождитесь "...."
        3. Получите "...."

        
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      placeholder: Четкое и сжатое описание того, что вы ожидали увидеть, если бы бага не было
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Если возможно, прикрепите скриншоты или видео
      placeholder: Вставьте сюда
    validations:
      required: false


  - type: textarea
    id: misc
    attributes:
      label: Любая дополнительная информация
      placeholder:
    validations:
      required: false
      
