name: Баг на сервере
description: Для tech-сервера
labels: 
  - unmarked
  - minecraft

body:
  - type: input
    id: name
    attributes:
      label: Опишите баг
      placeholder: Cжатое описание ошибки
    validations:
      required: true
    
  - type: textarea
    id: desc
    attributes:  
      label: Шаги для воспроизведения поведения
      placeholder: |
        1. Зайдите на tech-сервер
        2. Нажмите "...."
        3. Пройдите до "...."
        4. Получите "...."
        
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      placeholder: Четкое и сжатое описание того, что вы ожидали увидеть, если бы бага не было
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Если возможно, прикрепите скриншоты или видео
      placeholder: Вставьте сюда
    validations:
      required: false
      

  - type: textarea
    id: misc
    attributes:
      label: Любая дополнительная информация
      placeholder:
    validations:
      required: false
      
